_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.5
            "6": 4.19.2
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
architecture:
    value: Stablediffusion
batch_size:
    value: 128
data_path:
    value: path
dataset:
    value: russian-emoji
epoch_step:
    value: 3
epochs:
    value: 15
learning_rate:
    value: 0.0001
num_class:
    value: 10
